version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:yourpassword@db:5432/newdatabase
    env_file:
      - .env
    volumes:
      - .:/app

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: newdatabase
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourpassword
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
