name: Docker CI/CD

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build Docker Image
      run: |
        docker build . \
          --file Dockerfile \
          --tag joeuzo/billify:test-$(echo ${{ github.sha }} | cut -c1-7)
          
  push:
    if: github.event_name == 'push'  # && github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build Docker Image
      run: |
        docker build . \
          --file Dockerfile \
          --tag joeuzo/billify:$(echo ${{ github.sha }} | cut -c1-7) \
          --tag joeuzo/billify:latest
          

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login --username "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Push Docker Image
      run: |
        docker push joeuzo/billify:$(echo ${{ github.sha }} | cut -c1-7)
        docker push joeuzo/billify:latest
        
